name: BountyUI
main: BountyUI\Main
version: 1.2.0
api: 5.0.0
author: ZyberPE

depend:
 - EconomyAPI
 - FormAPI

commands:
  bounty:
    description: Open bounty menu
    permission: bounty.use

permissions:
  bounty.use:
    default: true
