name: BountyUI
main: BountyUI\Main
version: 1.2.0
api: 5.0.0
author: ZyberPE

depend:
 - EconomyAPI
 - FormAPI

commands:
  bounty:
    description: Open bounty menu
    permission: bounty.use
  topbounties:
    description: Manage bounty leaderboard
    permission: bountyui.admin

permissions:
  bountyui.admin:
    default: op
  bounty.use:
    default: true
